name: ManualTriggerHostedWF
on: workflow_dispatch
jobs:
  init-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Good Bye!!"
